export const ALL_LISTINGS = [
  {
    id: 'cs-delhi-1',
    name: 'Innovate Cowork Delhi',
    brand: 'WeWork',
    verified: true,
    images: ['https://images.unsplash.com/photo-1594465919365-17d5a5a5e3e0?q=80&w=2070&auto=format&fit=crop', 'https://images.unsplash.com/photo-1521737674892-fe5b5a7c8f29?q=80&w=2940&auto=format&fit=crop'],
    location: 'Connaught Place',
    city: 'Delhi',
    service: 'Coworking Space',
    budgetPerSeat: 8000,
    parking: ['car', 'bike'],
    metro_nearby: true,
  },
  {
    id: 'mr-gurgaon-1',
    name: 'Boardroom Pros Gurgaon',
    brand: 'Awfis',
    verified: true,
    images: ['https://images.unsplash.com/photo-1556761175-b413da4b2488?q=80&w=1974&auto=format&fit=crop'],
    location: 'Cyber City',
    city: 'Gurgaon',
    service: 'Meeting Room',
    budgetPerSeat: 500,
    parking: ['car', 'bike'],
    metro_nearby: true,
  },
  {
    id: 'vo-gurgaon-1',
    name: 'Virtual Presence Suites',
    brand: 'Regus',
    verified: true,
    images: ['https://images.unsplash.com/photo-1521737852577-6848d81b9324?q=80&w=2070&auto=format&fit=crop'],
    location: 'Golf Course Road',
    city: 'Gurgaon',
    service: 'Virtual Office',
    budgetPerSeat: 2000,
    parking: ['car'],
    metro_nearby: false,
  },
  {
    id: 'cs-bangalore-1',
    name: 'Koramangala Day Pass Hub',
    brand: 'WeWork',
    verified: true,
    images: ['https://images.unsplash.com/photo-1560421683-6223b448344a?q=80&w=1974&auto=format&fit=crop'],
    location: '102, 5th Block, Koramangala',
    city: 'Bangalore',
    service: 'Day Pass',
    budgetPerSeat: 600,
    parking: ['bike'],
    metro_nearby: true,
  },
  {
    id: 'tr-hyderabad-1',
    name: 'Hitech Training Facility',
    brand: 'Awfis',
    verified: false,
    images: ['https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=2070&auto=format&fit=crop'],
    location: 'Laxmi Cyber City',
    city: 'Hyderabad',
    service: 'Training Room',
    budgetPerSeat: 10000,
    parking: [],
    metro_nearby: false,
  },
   {
    id: 'mo-noida-1',
    name: 'Sector 62 Managed Office',
    brand: 'CoWrks',
    verified: true,
    images: ['https://images.unsplash.com/photo-1549923746-c502d488b3ea?q=80&w=2071&auto=format&fit=crop'],
    location: 'C-25, Sector 62',
    city: 'Noida',
    service: 'Managed Office',
    budgetPerSeat: 25000,
    parking: ['bike'],
    metro_nearby: true,
  },
];